// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAYdI3Pqb4z7PSiqMJ8J6CI6U1IQagC8',
    appId: '1:373790027911:web:961fc576ff97c271198822',
    messagingSenderId: '373790027911',
    projectId: 'programmer-prodigies',
    authDomain: 'programmer-prodigies.firebaseapp.com',
    databaseURL: 'https://programmer-prodigies-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programmer-prodigies.appspot.com',
    measurementId: 'G-ZTT747ZYWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKu9JCnQn9sVi0B8SUqv8_1tDIWKlMUN8',
    appId: '1:373790027911:android:ac7a01cab5e5d7e5198822',
    messagingSenderId: '373790027911',
    projectId: 'programmer-prodigies',
    databaseURL: 'https://programmer-prodigies-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programmer-prodigies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nUMLHhMuXp7FMUEtyk9Ezo7akly8evI',
    appId: '1:373790027911:ios:75df9e320d944672198822',
    messagingSenderId: '373790027911',
    projectId: 'programmer-prodigies',
    databaseURL: 'https://programmer-prodigies-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programmer-prodigies.appspot.com',
    iosBundleId: 'com.example.programmerProdigies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nUMLHhMuXp7FMUEtyk9Ezo7akly8evI',
    appId: '1:373790027911:ios:75df9e320d944672198822',
    messagingSenderId: '373790027911',
    projectId: 'programmer-prodigies',
    databaseURL: 'https://programmer-prodigies-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programmer-prodigies.appspot.com',
    iosBundleId: 'com.example.programmerProdigies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGAYdI3Pqb4z7PSiqMJ8J6CI6U1IQagC8',
    appId: '1:373790027911:web:2f683c88d15390ab198822',
    messagingSenderId: '373790027911',
    projectId: 'programmer-prodigies',
    authDomain: 'programmer-prodigies.firebaseapp.com',
    databaseURL: 'https://programmer-prodigies-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programmer-prodigies.appspot.com',
    measurementId: 'G-WZPWNE0LYG',
  );
}
